paths:
  data_raw: ./data/raw/wine-quality.csv
  data_processed: ./data/processed/processed.pkl
  monitoring:
    data_reference: ./data/monitoring/reference/reference.pkl
    drift_scenarios_dir: ./data/monitoring/drift_scenarios/
    evidently_reports_dir: ./reports/evidently/
  mlflow_db: ./mlflow.db
  mlruns: ./mlruns
mlflow:
  artifact_path: sklearn-model
  model_name: wine_quality_prediction
  experiment_name: wine_quality_prediction
ml:
  target_name: quality
  random_state: 42
monitoring:
  drift_scenarios_files:
    - feature_drift.csv
    - target_drift.csv
    - concept_drift.csv
