services:
  train:
    profiles: ["training"]
    build:
      context: .
      target: training
    container_name: wine_model_train
    working_dir: /app
    volumes:
      - ./:/app
    command: python -m src.training.run_training_pipeline

  evidently-report:
    profiles: ["monitoring"]
    build:
      context: .
      target: monitoring
    container_name: wine_evidently_report
    working_dir: /app
    volumes:
      - ./:/app
    command: python -m src.monitoring.evidently.generate_report

  api:
    build:
      context: .
      target: serving
    container_name: wine_api
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn src.serving.api:app --host 0.0.0.0 --port 8000

  prometheus:
    image: prom/prometheus:latest
    container_name: wine_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: wine_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./src/monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./src/monitoring/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./src/monitoring/grafana/dashboards:/etc/grafana/dashboards

volumes:
  grafana-storage: